function toggleMenu(){const menu=document.getElementById('menu');const main=document.getElementById('main');const toggleBtn=document.getElementById('toggle-btn');const isMobileScreen=window.matchMedia("only screen and (max-device-width: 480px)").matches;if(isMobileScreen){if(menu.style.left==='0px'){menu.style.left='-250px';main.style.marginLeft='0';toggleBtn.style.left='0';}else{menu.style.left='0';main.style.marginLeft='30vw';toggleBtn.style.left='30vw';}}else{if(menu.style.left==='0px'){menu.style.left='-250px';main.style.marginLeft='0';toggleBtn.style.left='0';}else{menu.style.left='0';main.style.marginLeft='16vw';toggleBtn.style.left='16vw';}}}
function openPopup(link){var popupContainer=document.getElementById('popupContainer');var isOpen=popupContainer.style.display==='block';if(isOpen){closePopup();}
popupContainer.style.display='block';document.body.style.overflow='hidden';var iframe=document.createElement('iframe');iframe.src='Codes/MenuPopups/'+link;popupContainer.appendChild(iframe);iframe.onload=function(){this.style.height=(this.contentDocument.body.scrollHeight)+'px';this.style.width=(this.contentDocument.body.scrollWidth)+'px';};}
function closePopup(){document.getElementById('popupContainer').style.display='none';document.body.style.overflow='';var iframe=document.querySelector('#popupContainer iframe');iframe.parentNode.removeChild(iframe);}
function updateData(){axios.get('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd').then(response=>{const bitcoinUSDValue=response.data.bitcoin.usd;const formattedBitcoinPrice=formatNumberWithSeparator(Math.floor(bitcoinUSDValue));document.getElementById('bitcoinPrice').innerHTML=`Bitcoin Price:<span style="color: #61dafb;">$${formattedBitcoinPrice}</span>&nbsp`;const satsPerDollar=Math.floor(100000000/bitcoinUSDValue);const formattedSatsPerDollar=formatNumberWithSeparator(satsPerDollar);document.getElementById('satsPerDollar').innerHTML=`|&nbspSats/$:<span style="color: #61dafb;">${formattedSatsPerDollar}</span>`;}).catch(error=>{console.error('Error fetching Bitcoin price:',error);});axios.get('https://blockchain.info/q/getblockcount').then(response=>{const blockHeight=response.data;document.getElementById('blockHeight').innerHTML=`|&nbspBlock Height:<span style="color: #61dafb;">${blockHeight.toLocaleString('en-US')}</span>&nbsp`;halvingcountdown=840000-blockHeight;if(halvingcountdown>=0){document.getElementById('halvingcountdown').innerHTML=`|&nbspBlocks Till Halving:<span style="color: #61dafb;">${halvingcountdown.toLocaleString('en-US')}</span>&nbsp`;}else{document.getElementById('halvingcountdown').innerHTML=``;}
let destroyedcoinbase=28.95502904;let finalsupply=20999999.97690000
let realcurrentsupply=0;let currentsupply=0;for(let i=0;i<Math.floor(blockHeight/210000);i++){const supplyInInterval=210000*(50/Math.pow(2,i));currentsupply+=supplyInInterval;}
const remainingBlocks=blockHeight%210000;const lastIntervalSupply=remainingBlocks*(50/Math.pow(2,Math.floor(blockHeight/210000)));currentsupply+=lastIntervalSupply;realcurrentsupply=currentsupply-destroyedcoinbase
let realfinalsupply=finalsupply-destroyedcoinbase
let percmined=realcurrentsupply/realfinalsupply*100
document.getElementById('currentsupply').innerHTML=`|&nbspCurrent Supply:<span style="color: #61dafb; font-weight: bold">${realcurrentsupply.toLocaleString('en-US',{minimumFractionDigits:8,maximumFractionDigits:8})}&nbsp(${percmined.toFixed(4)}%)</span>&nbsp`;document.getElementById('realfinalsupply').innerHTML=`|&nbspDiluted Supply:<span style="color: #61dafb; font-weight: bold">${realfinalsupply.toLocaleString('en-US',{minimumFractionDigits:8,maximumFractionDigits:8})}</span>`;}).catch(error=>{console.error('Error fetching block height:',error);});}
function txnfees(){axios.get('https://mempool.space/api/v1/fees/recommended').then(response=>{const feeRates=response.data;const lowPriority=feeRates.hourFee;const mediumPriority=feeRates.halfHourFee;const highPriority=feeRates.fastestFee;document.getElementById('feeRates').innerHTML=`|&nbspFees:Low Priority<span style="color: #61dafb;">${lowPriority}</span>Medium Priority<span style="color: #61dafb;">${mediumPriority}</span>HighPriority<span style="color: #61dafb;">${highPriority}</span>`;}).catch(error=>{console.error('Error fetching fee rates:',error);})};function formatNumberWithSeparator(number){return number.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");}
function closePopup(){document.getElementById('popupContainer').style.display='none';document.body.style.overflow='';var iframe=document.querySelector('#popupContainer iframe');if(iframe){iframe.parentNode.removeChild(iframe);}}
document.addEventListener('DOMContentLoaded',function(){updateData();setInterval(updateData,60000);});